import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Footer from '@/components/Footer'
const inter = Inter({ subsets: ['latin'] })
import Provider from '@/components/Provider'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
     <Provider>
        <Navbar />
        {children}
        <Footer />
    </Provider> 
     </body>
    </html>
  )
}
