import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Link from "next/link"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
      <main className='max-w-screen-sm m-auto h-screen'>
        <header>
          <nav className='flex justify-center mt-3'>
            <Link href="/" className='p-2 bg-amber-600 mr-3 w-32 text-center rounded-md'>Home</Link>
            <Link href="/createnote" className='p-2 bg-amber-600 w-32 text-center rounded-md'>New Note</Link>
          </nav>
        </header>
      <section className='max-w-full bg-neutral-900 p-4 mt-4 h-full rounded-md'>
        <ul className='max-w-lg	m-auto'>
          <li className='p-4 bg-neutral-950	mt-5 mb-4 rounded-md'>
            <p>Note Title</p>
            <h5>Note Content here just more note content here just more note contente here just more here</h5>
            <button className='mr-3 text-lime-700 mt-2 p-2'><i class="fa-solid fa-pen-to-square "></i></button>
            <button className='text-rose-600	p-2'><i class="fa-solid fa-trash"></i></button>
          </li>
          <li className='p-4 bg-neutral-950	mt-5 mb-4 rounded-md'>
            <p>Note Title</p>
            <h5>Note Content here just more note content here just more note contente here just more here</h5>
            <button className='mr-3 text-lime-700 mt-2 p-2'><i class="fa-solid fa-pen-to-square "></i></button>
            <button className='text-rose-600	p-2'><i class="fa-solid fa-trash"></i></button>
          </li>
          <li className='p-4 bg-neutral-950	mt-5 mb-4 rounded-md'>
            <p>Note Title</p>
            <h5>Note Content here just more note content here just more note contente here just more here</h5>
            <button className='mr-3 text-lime-700 mt-2 p-2'><i class="fa-solid fa-pen-to-square "></i></button>
            <button className='text-rose-600	p-2'><i class="fa-solid fa-trash"></i></button>
          </li>
          <li className='p-4 bg-neutral-950	mt-5 mb-4 rounded-md'>
            <p>Note Title</p>
            <h5>Note Content here just more note content here just more note contente here just more here</h5>
            <button className='mr-3 text-lime-700 mt-2 p-2'><i class="fa-solid fa-pen-to-square "></i></button>
            <button className='text-rose-600	p-2'><i class="fa-solid fa-trash"></i></button>
          </li>
        </ul>
      </section>
      </main>
    </>
  )
}
